# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 18:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acelibraryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='enroll_number',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='course',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='course_author',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='couse_des',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='link',
            new_name='URL',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='couse_diff',
        ),
        migrations.AddField(
            model_name='resources',
            name='Difficulty',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=69),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='resources',
            name='Category',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='acelibraryapp.Categories'),
            preserve_default=False,
        ),
    ]
