# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 15:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acelibraryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='Difficulty',
        ),
        migrations.AddField(
            model_name='tasks',
            name='difficulty',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
