# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acelibraryapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Resources',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='enroll_number',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
