# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 18:53
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('acelibraryapp', '0002_auto_20161116_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attended',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Aditya Dhawan'), (2, 'Ashish Pahwa'), (3, 'Desmond Miles'), (4, 'Vibhu Kesar'), (5, 'Nitesh Rai'), (6, 'Kartikey Tripathi'), (7, 'Nitish Arora'), (8, 'Debjeet Majumdar'), (9, 'Aarti Narang'), (10, 'Shourye Jain'), (11, 'Akshay Dureja'), (12, 'Anshul Bansal'), (13, 'Shubham Garg'), (14, 'Rajat Chaudhary'), (15, 'Mayank Khanduja'), (16, 'Rahul Gaur'), (17, 'Shubham Goria'), (18, 'Maniraj Singh Jadaun'), (19, 'Sameer Kumar'), (20, 'Rajeev Jha'), (21, 'Tanseer Saji'), (22, 'Arihant Jain'), (23, 'Himanshu Dua'), (24, 'Khushi Jain'), (25, 'Deepanshu Gupta'), (26, 'Mukesh Garg'), (27, 'Srijit S Madhavan'), (28, 'Harshit Jain'), (29, 'Harshit Jain'), (30, 'Bhavay Khanna'), (31, 'SriShti ShaRma'), (32, 'Rishi Dhamija'), (33, 'Ojasvee Bhardwaj'), (34, 'Shreyans Jain'), (35, 'Dhruv Goel'), (36, 'Tushar Sapra'), (37, 'Prapti Gupta'), (38, 'Devender Raghav'), (39, 'Viswajith Vellanki'), (40, 'Pulkit Goel'), (41, 'Ayush Gupta'), (42, 'Ashutosh Upadhyay'), (43, 'AAyush Gupta'), (44, 'Nitasha Bhatia'), (45, 'Harsh Vasudeva'), (46, 'Anukriti Gupta'), (47, '\xc3\u0192fyie'), (48, 'Prachi Garg'), (49, 'Prerna Sharma'), (50, 'Rohit Kumar'), (51, 'Tushar Ahuja'), (52, 'Ashu R. Kumar'), (53, 'Anurag Panwar'), (54, 'Gursimrat Singh'), (55, 'Shubh Dhawan'), (56, 'Rohan Tyagi'), (57, 'S\xc3\xa0rth\xc3\xa2k Kh\xc3\xa1\xc3\xb1d\xc3\xaalw\xc3\xa3l'), (58, 'Swarndeep Singh'), (59, 'Jobin Sabu'), (60, 'AdiTya Raman'), (61, 'Nimit Pahwa'), (62, 'Devansh Gupta'), (63, 'Marshall Gaurav'), (64, 'Kaps Gera'), (65, 'Prabhupada Mohanty'), (66, 'Sharad Gaur'), (67, 'Himanshu Chauhan'), (68, 'Shivam Agarwal'), (69, 'Rahul Kumar Jha'), (70, 'Yugansh Tyagi'), (71, 'Afzal Ahmed'), (72, 'Aditya Agrawal'), (73, 'Taran Deep'), (74, 'Saloni Garg'), (75, 'Akshita Gupta'), (76, 'Kartik Gupta'), (77, 'Kuldeep Singh Malik'), (78, 'Raunak Sett'), (79, 'Nishant Rajput'), (80, 'UdIt MiTtal'), (81, 'Sagar Bansal'), (82, 'Sawal Kalra'), (83, 'Suman Saurav Sharma'), (84, 'Sahil Singh'), (85, 'Arjun'), (86, 'Ajay Mahor'), (87, 'Gaurav Saini'), (88, 'Vishal Dharan'), (89, 'Avi Dhawan'), (90, 'Vaibhav Suri'), (91, 'Chirag Dudheria'), (92, 'Dhruv Shah'), (93, 'Harshit Garg'), (94, 'Gaurav Taneja'), (95, 'Kartik Ahuja'), (96, 'Neeraj Kumar'), (97, 'Shubhangi Gupta'), (98, 'Sahil Bhatia'), (99, 'Nitin Mishra'), (100, 'Khushank Raj'), (101, 'Gaurav Gogia'), (102, 'Kanav Kumar'), (103, 'Phinehas Ratnam'), (104, 'Arpan Gupta'), (105, 'Ankit Tayal'), (106, 'Ankit Tayal'), (107, 'Vikrant Barul'), (108, 'Mayank Jain'), (109, 'Sahil Khan'), (110, 'Siddharth Sethi'), (111, 'Lakshay Grover'), (112, 'Charvi Wadhwa'), (113, 'Lakshay Sharma'), (114, 'Rizwan Ali'), (115, 'Kandarp Gautam'), (116, 'Anmol Gro Ver'), (117, 'Syed Ahsan Shahid'), (118, 'Dhruv Shah'), (119, 'Lakhin Gupta'), (120, 'Sumit Malik'), (121, 'Sawal Kalra'), (122, 'Shibam Mukherjee'), (123, 'Shreya Vijhani'), (124, 'Shreya Jain'), (125, 'Sankarshan Kohli'), (126, 'Amritasha Chhabra'), (127, 'Sanil Khurana'), (128, 'Palak Joshi'), (129, 'Soumya Kohli'), (130, 'Jaskirat Singh'), (131, 'Akshay Katyal'), (132, 'Umang Khandelwal'), (133, 'Saloni Garg'), (134, 'Sumit Arora'), (135, 'Shivangi Jain'), (136, 'Shruti Jain'), (137, 'Arsh Saxena'), (138, 'Ayushi Gupta'), (139, 'Priya Mittal'), (140, 'Ashu Jaiswal'), (141, 'Apram Lamba'), (142, 'Mukesh Sharma'), (143, 'Vatsal Papne'), (144, 'Shlagha Gulati'), (145, 'Richa Gupta'), (146, 'Shiv Aggarwal'), (147, 'Rohan Kumar'), (148, 'Aditi Mishra')], max_length=483),
        ),
    ]
