# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acelibraryapp', '0003_auto_20161113_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='cat',
            field=models.ForeignKey(default='bla', on_delete=django.db.models.deletion.CASCADE, to='acelibraryapp.Categories'),
            preserve_default=False,
        ),
    ]
