# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 19:16
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('acelibraryapp', '0004_auto_20161117_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attended',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(43, 'AAyush Gupta'), (9, 'Aarti Narang'), (60, 'AdiTya Raman'), (148, 'Aditi Mishra'), (1, 'Aditya Dhawan'), (11, 'Akshay Dureja'), (126, 'Amritasha Chhabra'), (106, 'Ankit Tayal'), (12, 'Anshul Bansal'), (46, 'Anukriti Gupta'), (2, 'Ashish Pahwa'), (42, 'Ashutosh Upadhyay'), (91, 'Chirag Dudheria'), (8, 'Debjeet Majumdar'), (3, 'Desmond Miles'), (62, 'Devansh Gupta'), (35, 'Dhruv Goel'), (92, 'Dhruv Shah'), (94, 'Gaurav Taneja'), (54, 'Gursimrat Singh'), (93, 'Harshit Garg'), (28, 'Harshit Jain'), (67, 'Himanshu Chauhan'), (23, 'Himanshu Dua'), (59, 'Jobin Sabu'), (102, 'Kanav Kumar'), (115, 'Kandarp Gautam'), (95, 'Kartik Ahuja'), (6, 'Kartikey Tripathi'), (24, 'Khushi Jain'), (119, 'Lakhin Gupta'), (113, 'Lakshay Sharma'), (18, 'Maniraj Singh Jadaun'), (15, 'Mayank Khanduja'), (26, 'Mukesh Garg'), (44, 'Nitasha Bhatia'), (99, 'Nitin Mishra'), (103, 'Phinehas Ratnam'), (48, 'Prachi Garg'), (49, 'Prerna Sharma'), (139, 'Priya Mittal'), (16, 'Rahul Gaur'), (20, 'Rajeev Jha'), (32, 'Rishi Dhamija'), (81, 'Sagar Bansal'), (98, 'Sahil Bhatia'), (109, 'Sahil Khan'), (74, 'Saloni Garg'), (19, 'Sameer Kumar'), (127, 'Sanil Khurana'), (125, 'Sankarshan Kohli'), (82, 'Sawal Kalra'), (66, 'Sharad Gaur'), (122, 'Shibam Mukherjee'), (10, 'Shourye Jain'), (124, 'Shreya Jain'), (34, 'Shreyans Jain'), (136, 'Shruti Jain'), (55, 'Shubh Dhawan'), (17, 'Shubham Goria'), (97, 'Shubhangi Gupta'), (110, 'Siddharth Sethi'), (27, 'Srijit S Madhavan'), (134, 'Sumit Arora'), (117, 'Syed Ahsan Shahid'), (21, 'Tanseer Saji'), (73, 'Taran Deep'), (51, 'Tushar Ahuja'), (80, 'UdIt MiTtal'), (4, 'Vibhu Kesar'), (70, 'Yugansh Tyagi'), (47, '\xc3\u0192fyie')], max_length=226),
        ),
    ]
