# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acelibraryapp', '0005_auto_20161117_0046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
