# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 14:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acelibraryapp', '0006_delete_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='difficulty',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='resources',
            name='imgUrl',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
