# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acelibraryapp', '0007_auto_20161120_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='Type',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resources',
            name='Description',
            field=models.TextField(max_length=500),
        ),
    ]
