# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acelibraryapp', '0008_auto_20161120_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='URL',
            field=models.CharField(max_length=150),
        ),
    ]
